### ISSUE TITLE
Issue #0001 - Secciones con dos ciclos no se tienen en cuenta adecuadamente

### ISSUE THREAD

**Issue by SergioZona** [Open-Source-Uniandes/Mi-Horario-Uniandes#1]
No se tiene en cuenta, cuando las materias son de ciclo 1 y ciclo 2, lo que fuerza a que el algoritmo las ponga en franjas horarias distintas aún cuando no es necesario.

**Comment by c4ts0up** [comment]
Adicionalmente, para algunas secciones de ciclo 2, su título se cambia erróneamente en el cuadro del _Paso 3_ al ser seleccionadas en el _Paso 1_. Esto pasa, por ejemplo, para la **sección 41 de Escritura Universitaria II** (NRC `51647`). Sin embargo, no pasa para todas las secciones de ciclo 2. Por ejemplo, para la **sección 1 de Contexto Patrimonial ...** (NRC `33791`) este no es el caso.

**Comment by c4ts0up** [comment]
Ya tengo la solución para este problema. Estoy puliendo los últimos detalles.
