### ISSUE TITLE
Error bloques de tiempo reservado

### ISSUE THREAD

**Issue by ddi4z** [Open-Source-Uniandes/Mi-Horario-Uniandes#41]
Parece haber un error al crear bloques y mirar las combinaciones de horario.

**Comment by jsurrea** [comment]
Podrías darme un ejemplo para reproducirlo?

**Comment by ddi4z** [comment]
![image](https://github.com/Open-Source-Uniandes/Mi-Horario-Uniandes/assets/110594320/6c92733e-8306-45e1-86f6-3d006113f744)
![image](https://github.com/Open-Source-Uniandes/Mi-Horario-Uniandes/assets/110594320/c177e21c-dbff-4d7f-a3e7-d79b0eb4fb76)

**Comment by ddi4z** [comment]
![image](https://github.com/Open-Source-Uniandes/Mi-Horario-Uniandes/assets/110594320/76f0e57a-04ab-41a5-a23f-0acaa2dc160e)
Ocurre tambien aunque no haya cruce

**Comment by jsurrea** [comment]
Podrías revisar si ahora funciona correctamente? Gracias!

**Comment by ddi4z** [comment]
Todo parece funcionar correctamente :)
