### ISSUE TITLE
Issue #0005 - Usabilidad al cargar combinaciones de horario

### ISSUE THREAD

**Issue by SergioZona** [Open-Source-Uniandes/Mi-Horario-Uniandes#5]
Mostrar al usuario con algún método de carga, que la página está cargando los horarios y que por favor espere pacientemente.

**Comment by jsurrea** [comment]
¿Esto es en la sección de configuración, después de agregar cursos y bloques al presionar "Construir tu horario?
En mis pruebas esto no toma nada de tiempo

**Comment by SergioZona** [comment]
Al ingresar materias con muchas secciones, como cálculos, escrituras y físicas, genera demasiadas combinaciones posibles de horarios (si es que se agregan casi todas las secciones de estos cursos), eso provoca que la carga para renderizar el horario sea demorada. 

Aquí un ejemplo: 
![image](https://user-images.githubusercontent.com/60414505/212180016-0e54a0a9-c08d-4947-a815-7ebd2a6de5b5.png)

No es algo que afecte mucho la funcionalidad, pero sería bueno al usuario notificarle de algún modo que el horario está cargando (para que no piense que la página se murió).

**Comment by jsurrea** [comment]
Perfect, thanks!
