### ISSUE TITLE
Issue #0007 - Colores al llegar al último horario

### ISSUE THREAD

**Issue by SergioZona** [Open-Source-Uniandes/Mi-Horario-Uniandes#7]
Si uno le da a la derecha en el último horario, vuelve a renderizar y cambia de colores creando un ataque de epilepsia. Ojito xd.

**Comment by abelarismendy** [comment]
Una vez se añaden los bloques en el paso 2, no se pueden modificar o eliminar.

**Comment by jsurrea** [comment]
Ojito, solucionado 👀
